version: '3'
services:
  web:
    build: .
    image: web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TZ: "Europe/Moscow"
    restart: always
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /etc/ssl/crm.example.ru:/etc/ssl/crm.example.ru
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"